# Generated by Django 4.1.6 on 2023-02-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_final',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(max_length=100)),
                ('img_link', models.CharField(default='', max_length=100)),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
